import PrintHelper
PrintHelper.PrintTitle('(tuples)')
PrintHelper.PrintSubtitle('()不是必须的')
print('t=\"apple\",\"banana\"')
print('等同于')
print('t=(\"apple\",\"banana\")')
PrintHelper.PrintSubtitle('层级可以多层嵌套')
print('t2=(\"apple\",3,1.41213,(\"banana\",5))')
PrintHelper.PrintTitle('查看类型')
PrintHelper.PrintCode('t=(\"apple\",5)')
PrintHelper.PrintCode('print(type(t))')
t=("apple",5)
print(type(t))
PrintHelper.PrintTitle('查看元素个数')
PrintHelper.PrintCode('print(len(t))')
print(len(t))
PrintHelper.PrintTitle('遍历元组')
PrintHelper.PrintSubtitle('示例while')
PrintHelper.PrintCode('t=(\"apple\",5)')
PrintHelper.PrintCode('i=0')
PrintHelper.PrintCode('while i<len(t):')
PrintHelper.PrintCode('    print(t[i])')
t=("apple",5)
i=0
while i<len(t):
    print(t[i])
    i+=1
PrintHelper.PrintSubtitle('示例for')
PrintHelper.PrintCode('t=(\"apple\",5)')
PrintHelper.PrintCode('for item in t:')
PrintHelper.PrintCode('    print(item)')
t=("apple",5)
for item in t:
    print(item)
PrintHelper.PrintSubtitle('元组间的比较')
PrintHelper.PrintCode('t1=(\"apple\",\"banana\")')
PrintHelper.PrintCode('t2=(\"apple\",\"cherry\")')
PrintHelper.PrintCode('print(t1>t2)')
t1=("apple","banana")
t2=("apple","cherry")
print(t1>t2)
PrintHelper.PrintSubtitle('元组数据项不可更改')
print('以下语句将抛出异常')
print('t1=(\"apple\",\"banana\")')
print('t1[0]=\"orange\"')
PrintHelper.PrintSubtitle('检查远足是否包含数据项')
PrintHelper.PrintCode('t=(\"apple\",\"banana\")')
PrintHelper.PrintCode('print(\"apple\" in t)')
t=("apple","banana")
print("apple" in t)
