titlePattern=":-^80"
contentPattern=":10"
print(("{"+titlePattern+"}").format("Value Expressions"))
print("+   addition")
print("-   substraction")
print("*   multiplication")
print("/   division")
print("//  integer division")
print("**  power")
print("%   modulo")
print(("{"+titlePattern+"}").format("Samples"))
print(("{"+contentPattern+"}").format("1+2=?"),1+2)
print(("{"+contentPattern+"}").format("1-2=?"),1-2)
print(("{"+contentPattern+"}").format("4*5=?"),4*5)
print(("{"+contentPattern+"}").format("14/5=?"),14/5)
print(("{"+contentPattern+"}").format("14//5=?"),14//5)
print(("{"+contentPattern+"}").format("2**3=?"),2**3)
print(("{"+contentPattern+"}").format("8%3=?"),8%3)
print(("{"+titlePattern+"}").format("String Expressions"))
print("+   addition")
print("*   multiplication")
print(("{"+titlePattern+"}").format("Samples"))
print(("{"+contentPattern+"}").format("'1'+'2'=?"),'1'+'2')
print(("{"+contentPattern+"}").format("'123'*3=?"),'123'*3)
print(("{"+titlePattern+"}").format("Type Casting Expressions"))
print("int()")
print("float()")
print("str()")
print(("{"+titlePattern+"}").format("Samples"))
print(("{"+contentPattern+"}").format("int('1')=?"),int('1'))
print(("{"+contentPattern+"}").format("float('1')=?"),float('1'))
print(("{"+contentPattern+"}").format("str(1)=?"),str(1))

