import PrintHelper
PrintHelper.PrintTitle('Comma-Separated Values(CSV)')
print('CSV是最常用的用于电子制表文件和数据库导入导出数据的文本文件类型')
print('标准的格式是每行都有一个记录,一个记录就是一个完整对象,对象的字段之间用逗号分隔')
print('首行可能由字段名称组成.')
print('以下是一个打开CSV文件的示例')
print('fp = open( \"pc_inventory.csv\" )')
print('print( fp.read().strip() )')
print('fp.close()')
PrintHelper.PrintHint('csv模块,用于CSV文件的处理')
PrintHelper.PrintHint('csv.reader(@FileHandler)')
print('import csv')
print('fh=open( \"pc_inventory.csv\", newline= \' \' )')
print('reader=reader(fh)')
print('for line in reader:')
print('    print(line)')
print('fh.close()')
PrintHelper.PrintHint('csv.writer(@FileHandler)')
print('from csv import writer')
print('fp = open( \"pc_writetest.csv\", \"w\", newline= \' \' )')
print('csvwriter = writer( fp )')
print('csvwriter.writerow( [\"MOVIE\", \"RATING\"] )')
print('csvwriter.writerow( [\"Monty Python and the Holy Grail\", 8] )')
print('csvwriter.writerow( [\"Monty Python \'s Life of Brian\", 8.5] )')
print('csvwriter.writerow( [\"Monty Python \'s Meaning of Life\", 7] )')
print('fp.close()')
PrintHelper.PrintTitle('Pickling,酸洗,混合大对象整体处理')
PrintHelper.PrintHint('pickle模块')
PrintHelper.PrintHint('pickle.dump(@value,@fileHandler)')
print('from pickle import dump')
print('cheeseshop = [ (\"Roquefort\", 12, 15.23), (\"White Stilton\", 25, 19.02), (\"Cheddar\", 5, 0.67) ]')
print('fp = open( \"pc_cheese.pck\", \"wb\" )')
print('dump( cheeseshop, fp )')
print('fp.close()')
PrintHelper.PrintHint('buffer=pickle.load(@fileHandler)')
print('from pickle import load')
print('fp = open( \"pc_cheese.pck\", \"rb\" )')
print('buffer = load( fp )')
print('fp.close()')
PrintHelper.PrintTitle('JavaScript Object Notation(JSON)')
PrintHelper.PrintHint('json模块,JSON算是Pickling技术的一种')
PrintHelper.PrintHint('json.dump(@value,@fileHandler)')
print('from json import dump, load')
print('cheeseshop = [ (\"Roquefort\", 12, 15.23)')
print('               , (\"White Stilton\", 25, 19.02)')
print('               , (\"Cheddar\", 5, 0.67) ]')
print('fp = open( \"pc_cheese.json\", \"w\" )')
print('dump( cheeseshop, fp )')
print('fp.close()')
PrintHelper.PrintHint('@value=json.load(@fileHandler)')
print('fp = open( \"pc_cheese.json\", \"r\" )')
print('buffer = load( fp )')
print('fp.close()')
PrintHelper.PrintTitle('HTML And XML')
print('HTML和XML也是标准的网页信息格式')
print('你可以使用正则来解析这些格式化的数据')
print('\"beautiful soup\"模块可以用于处理此类结构')
print('\"beautiful soup\"的最新模块名称是bs4,早前的有bs3,当然bs4更新')
print('bs4并不是标准的python包,你需要额外的安装它,这稍微有点麻烦')
print('python3提供了内置模块pip')
print('这方面有很多选择,比如lxml模块等等,而\"beautiful soup\"是最热门的')
