import PrintHelper
PrintHelper.PrintTitle('ReservedWords')
print('and')
print('as')
print('assert')
print('break')
print('class')
print('continue')
print('def')
print('del')
print('elif')
print('else')
print('except')
print('exec')
print('finally')
print('for')
print('from')
print('global')
print('if')
print('import')
print('in')
print('is')
print('lambda')
print('not')
print('or')
print('pass')
print('print')
print('raise')
print('return')
print('try')
print('while')
print('with')
print('yield')
titlePattern=":-^80"
contentPattern=":10"
print(("{"+titlePattern+"}").format("Shorthand Operators"))
print((("{"+contentPattern+"}")*3).format("+=","a+=b","a=a+b"))
print((("{"+contentPattern+"}")*3).format("-=","a-=b","a=a-b"))
print((("{"+contentPattern+"}")*3).format("*=","a*=b","a=a*b"))
print((("{"+contentPattern+"}")*3).format("/=","a/=b","a=a/b"))
print(("{"+titlePattern+"}").format("Samples"))
a=1
a+=2
print(("{"+contentPattern+"}").format("1+=2"),a)
b=3
b-=2
print(("{"+contentPattern+"}").format("3-=2"),b)
c=5
c*=3
print(("{"+contentPattern+"}").format("5*=3"),c)
d=6
d/=4
print(("{"+contentPattern+"}").format("6/=4"),d)
