titlePattern=":-^80"
contentPattern=":30"
print(("{"+titlePattern+"}").format("Type Casting"))
print(("{"+contentPattern+"}").format("float(@value)"))
print(("{"+contentPattern+"}").format("int(@value)"))
print(("{"+contentPattern+"}").format("str(@value)"))
print(("{"+titlePattern+"}").format("Samples"))
print(("{"+contentPattern+"}").format("float('1')"),float('1'))
print(("{"+contentPattern+"}").format("int('2')"),int('2'))
print(("{"+contentPattern+"}").format('string(123)'),str(123))

print(("{"+titlePattern+"}").format("Calculations"))
print(("{"+contentPattern+"}").format("abs(@value)"))
print(("{"+contentPattern+"}").format("max(@value1,@value2[,@value_n])"))
print(("{"+contentPattern+"}").format("min(@value1,@value2[,@value_n])"))
print(("{"+contentPattern+"}").format("pow(@base,@logarithm)"))
print(("{"+contentPattern+"}").format("round(@float)"))
print(("{"+titlePattern+"}").format("Samples"))
print(("{"+contentPattern+"}").format("abs(-123)"),abs(-123))
print(("{"+contentPattern+"}").format("max(124,42,734)"),max(124,42,734))
print(("{"+contentPattern+"}").format("min(145,28,1)"),min(145,28,1))
print(("{"+contentPattern+"}").format("pow(2,3)"),pow(2,3))
print(("{"+contentPattern+"}").format("round(1.2345)"),round(1.2345))
print(("{"+titlePattern+"}").format("Others"))
print(("{"+contentPattern+"}").format("len(@string)"))
print(("{"+contentPattern+"}").format("input()"))
print(("{"+contentPattern+"}").format("print(@value1,@value2[,@value_n])"))
print(("{"+contentPattern+"}").format("@patternString.format(@value1[,@value_n])"))
print(("{"+titlePattern+"}").format("Samples"))
print(("{"+contentPattern+"}").format("len('123')"),len('123'))
print(("{"+contentPattern+"}").format("input()"),"please type any words and press enter")
value=input()
print(("{"+contentPattern+"}").format("you typed "),value)
print(("{"+contentPattern+"}").format("print()"),'we are always using print()')
print(("{"+contentPattern+"}").format("'{:.3f}'.format(7/11)"),'{:.3f}'.format(7/11))
print(("{"+contentPattern+"}").format("'{}{}{}'.format(1,2,3)"), '{}{}{}'.format(1,2,3))
print(("{"+contentPattern+"}").format("'{2}{1}{0}'.format(1,2,3)"), '{2}{1}{0}'.format(1,2,3))
print(("{"+contentPattern+"}").format("'{:-<20}'.format('value')"), '{:-<20}'.format('value'))
print(("{"+contentPattern+"}").format("'{:-^20}'.format('value')"), '{:-^20}'.format('value'))
print(("{"+contentPattern+"}").format("'{:->20}'.format('value')"), '{:->20}'.format('value'))
print(("{"+contentPattern+"}").format("'{:d}'.format(123)"), '{:d}'.format(123))
print(("{"+contentPattern+"}").format("'{:<15d}'.format(123)"), '{:15d}'.format(123))
print(("{"+contentPattern+"}").format("'{:f}'.format(123)"), '{:f}'.format(123))
print(("{"+contentPattern+"}").format("'{:>15f}'.format(123)"), '{:15f}'.format(123))
